/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_temple_cla_wolfgang_jnisvmlight_SVMLight */

#ifndef _Included_edu_temple_cla_wolfgang_jnisvmlight_SVMLight
#define _Included_edu_temple_cla_wolfgang_jnisvmlight_SVMLight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_temple_cla_wolfgang_jnisvmlight_SVMLight
 * Method:    svmTrain
 * Signature: (Ledu/temple/cla/wolfgang/jnisvmlight/SVMProblem;Ledu/temple/cla/wolfgang/jnisvmlight/SVMParameter;)Ledu/temple/cla/wolfgang/jnisvmlight/SVMModel;
 */
JNIEXPORT jobject JNICALL Java_edu_temple_cla_wolfgang_jnisvmlight_SVMLight_svmTrain
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     edu_temple_cla_wolfgang_jnisvmlight_SVMLight
 * Method:    svmPredict
 * Signature: (Ledu/temple/cla/wolfgang/jnisvmlight/SVMModel;[Ledu/temple/cla/wolfgang/jnisvmlight/SVMNode;)D
 */
JNIEXPORT jdouble JNICALL Java_edu_temple_cla_wolfgang_jnisvmlight_SVMLight_svmPredict
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
