/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_temple_cla_wolfgang_jnisvmlight_SVMLight */

#ifndef _Included_edu_temple_cla_wolfgang_jnisvmlight_SVMLight
#define _Included_edu_temple_cla_wolfgang_jnisvmlight_SVMLight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_temple_cla_wolfgang_jnisvmlight_SVMLight
 * Method:    SVMLearn
 * Signature: (Ljava/util/List;[DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_temple_cla_wolfgang_jnisvmlight_SVMLight_SVMLearn
  (JNIEnv *, jobject, jobject, jdoubleArray, jstring);

/*
 * Class:     edu_temple_cla_wolfgang_jnisvmlight_SVMLight
 * Method:    SVMClassify
 * Signature: (Ljava/lang/String;Ljava/util/List;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_temple_cla_wolfgang_jnisvmlight_SVMLight_SVMClassify
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
