/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_temple_cla_wolfgang_jnisvmlight_SVMLight */

#ifndef _Included_edu_temple_cla_wolfgang_jnisvmlight_SVMLight
#define _Included_edu_temple_cla_wolfgang_jnisvmlight_SVMLight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_temple_cla_wolfgang_jnisvmlight_SVMLight
 * Method:    SVMLearn
 * Signature: ([Ledu/temple/cla/wolfgang/jnisvmlight/Doc;[D)Ledu/temple/cla/wolfgang/jnisvmlight/Model;
 */
JNIEXPORT jobject JNICALL Java_edu_temple_cla_wolfgang_jnisvmlight_SVMLight_SVMLearn
  (JNIEnv *, jobject, jobject, jdoubleArray);

/*
 * Class:     edu_temple_cla_wolfgang_jnisvmlight_SVMLight
 * Method:    SVMClassify
 * Signature: (Ledu/temple/cla/wolfgang/jnisvmlight/Model;[Ledu/temple/cla/wolfgang/jnisvmlight/Doc;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_temple_cla_wolfgang_jnisvmlight_SVMLight_SVMClassify
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
